# Generated by Django 3.2.4 on 2021-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('TS', 'Танки'), ('HS', 'Хилы'), ('DD', 'ДД'), ('MS', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='TS', max_length=20, verbose_name='Категория'),
        ),
    ]
