# Generated by Django 3.2.4 on 2021-07-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Содержание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardapp.cuser', verbose_name='Автор')),
            ],
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
