# Generated by Django 3.2.4 on 2021-07-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20210701_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertreply',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardapp.advert', verbose_name='Объявление'),
        ),
    ]
