# Generated by Django 3.2.4 on 2021-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_advertreply_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertreply',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
