# Generated by Django 3.2.4 on 2021-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_alter_advert_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
    ]
